# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jbang:
    runs-on: ubuntu-latest
    name: convert
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/cache@v1
      with:
        path: /root/.jbang
        key: $-jbang-$
        restore-keys: |
            $-jbang-
    - name: "pull 5etools"
      run: |
        apt-get update; apt-get -y install curl unzip zip
        curl -L https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/releases/download/${VERSION_5ETOOLS}/5etools-${VERSION_5ETOOLS}.zip -o 5etools.zip
        mkdir 5etools
        unzip -q 5etools.zip -d 5etools || echo "unzip finished with errors. yolo."
    - name: jbang
      uses: jbangdev/jbang-action@v0.99.1
      with:
        trust: https://jitpack.io/dev/ebullient/json5e-convert-cli
        script: https://jitpack.io/dev/ebullient/json5e-convert-cli/1.0.16/json5e-convert-cli-1.0.16-runner.jar
        scriptargs: "-o collapsed_no_images -s $SOURCES 5etools/data"
      env:
        JBANG_REPO: /root/.jbang/repository
        GITHUB_TOKEN: $
        SOURCES: "PHB,DMG,MM,LMoP"
        JSON5E_CONVERT_CLI_VERSION: "1.0.16"
