name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION_5ETOOLS: "v1.169.1"
  JSON5E_CONVERT_CLI_VERSION: "1.0.16"
  SOURCES: "PHB,DMG,MM,LMoP"
jobs:
  jbang:
    runs-on: ubuntu-latest
    name: convert
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/cache@v1
      with:
        path: /root/.jbang
        key: $-jbang-$
        restore-keys: |
            $-jbang-
    - name: "pull 5etools"
      run: |
        sudo apt-get update; sudo apt-get -y install curl unzip zip
        curl -L https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/releases/download/${{ env.VERSION_5ETOOLS }}/5etools-${{ env.VERSION_5ETOOLS }}.zip -o 5etools.zip
        mkdir 5etools
        unzip -q 5etools.zip -d 5etools || echo "unzip finished with errors. yolo."
        
        # Build list of books + adventures (space-separated), setup execution
        BOOKS=$(echo $(find "5etools/data/book" | tail -n +2))
        ADVENTURES=$(echo $(find "5etools/data/adventure" | tail -n +2))

        echo "BOOKS=$BOOKS" >> $GITHUB_ENV
        echo "ADVENTURES=$ADVENTURES" >> $GITHUB_ENV
    - name: jbang
      uses: jbangdev/jbang-action@v0.99.1
      with:
        trust: https://jitpack.io/dev/ebullient/json5e-convert-cli
        script: https://jitpack.io/dev/ebullient/json5e-convert-cli/${{ env.JSON5E_CONVERT_CLI_VERSION }}/json5e-convert-cli-${{ env.JSON5E_CONVERT_CLI_VERSION }}-runner.jar
        scriptargs: "-o collapsed_no_images -s ${{ env.SOURCES }} 5etools/data ${{ env.BOOKS }} ${{ env.ADVENTURES }}"
      env:
        JBANG_REPO: /root/.jbang/repository
        GITHUB_TOKEN: $
    - name: compress
      run: zip -q -r collapsed_sources_no_images.zip collapsed_no_images
    - uses: actions/upload-artifact@v3
      with:
        name: collapsed_sources_no_images
        path: collapsed_sources_no_images.zip
